#!/usr/bin/env ruby

require 'pg_utils'

PgUtils.configure_with('config/pg_utils.yml')
if ARGV.first
  str = ARGV.first.strip
  if str == 'backup'
    ::PgUtils::Backup.new().run()
  elsif
    ::PgUtils::Restore.new().run()
  end
end
